/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 * Once you make a change to your contracts, run `yarn deploy` to update this file.
 */

import type { GenericContractsDeclaration } from "../types/index";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
